## Слова — это числа. Матрица — это карта смыслов

In [1]:
import pandas as pd

df = pd.read_csv("hf://datasets/brunokreiner/genius-lyrics/english_lyrics_some_with_genres.csv")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Датасет: Genius Song Lyrics
План работы:

  1) Предобработка датасета

In [2]:
df.iloc[14440:14445]

,Unnamed: 0,id,lyrics,is_english,genres_list,popularity,release_date,artist_id,artist_name,artist_popularity,artist_followers,artist_picture_url
14440,14457,6QXSnJrzhL07EdB8zo1f7L,she said go ahead and get out low down dirty b...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14441,14458,1IFXOMegTvZBlO94x8txam,hey little girl you know you stole my heart ba...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14442,14459,3WqCNJU0Fit5FFo7UdSEXM,and i held the breath inside my lungs for days...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14443,14460,2atxQgDDKhsFzDJLKwiGVp,i can t take you with me where i m goin in me ...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14444,14461,31RblOSHrkgNdpvI7ULoWC,when you you get through whatever it is you be...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.shape

(480855, 12)

нужны песни и жанры, почистим датасет

In [4]:
df.columns

Index(['Unnamed: 0', 'id', 'lyrics', 'is_english', 'genres_list', 'popularity',
       'release_date', 'artist_id', 'artist_name', 'artist_popularity',
       'artist_followers', 'artist_picture_url'],
      dtype='object')

In [5]:
df.drop(['Unnamed: 0', 'release_date', 'artist_id', 'artist_followers', 'artist_picture_url'], inplace = True, axis = 1)
df.drop(['popularity', 'artist_popularity'], inplace=True, axis=1)

In [6]:
df.head()

,id,lyrics,is_english,genres_list,artist_name
0,5FDh0G5oQ2UD9JxWiDCT1x,paper doll come try it on step out of that bla...,True,NaN,NaN
1,6XK6Zw6JkFsHXzAcMWNiIr,on my way on my way on my way on my way i woul...,True,NaN,NaN
2,7GX5flRQZVHRAGd6B4TmDO,are you alright i m alright i m quite alright ...,True,"['melodic rap', 'philly rap', 'rap', 'trap']",Lil Uzi Vert
3,73q3FpQVXWk5eSUnyo83E4,it s tearin up my heart when i m with you but ...,True,NaN,NaN
4,1IdTIzkTK6CcpKKgMUGbg7,some of us we re hardly ever here the rest of ...,True,NaN,NaN

In [7]:
import ast

# Convert string representation of list to actual list, handle NaNs
def parse_genres(genres_str):
    if pd.isna(genres_str):
        return []
    try:
        return ast.literal_eval(genres_str)
    except (ValueError, SyntaxError):
        return []

df['parsed_genres'] = df['genres_list'].apply(parse_genres)

# Flatten the list of lists into a single list of all genres
all_genres = [genre for sublist in df['parsed_genres'] for genre in sublist]

# Count the occurrences of each genre
genre_counts = pd.Series(all_genres).value_counts()

print("Occurrences of each genre:")
display(genre_counts.head(20))

Occurrences of each genre:

Unknown genre        4352
rock                 3762
hip hop              2367
rap                  2154
dance pop            2151
pop rock             2062
classic rock         1969
mellow gold          1913
country rock         1872
indie rock           1871
alternative rock     1866
pop rap              1855
country              1617
singer-songwriter    1599
adult standards      1596
pop                  1577
soft rock            1554
alternative metal    1546
modern rock          1505
gangster rap         1460
Name: count, dtype: int64

In [8]:
df = df[ df['is_english'] == True]
df = df.dropna(subset=['genres_list'])

In [9]:
df.shape

(49985, 6)

In [10]:
df

,id,lyrics,is_english,genres_list,artist_name,parsed_genres
2,7GX5flRQZVHRAGd6B4TmDO,are you alright i m alright i m quite alright ...,True,"['melodic rap', 'philly rap', 'rap', 'trap']",Lil Uzi Vert,"[melodic rap, philly rap, rap, trap]"
6,50YQFbfIVk2XMnVFKAuuib,we pick up in new york city i m tryna find a m...,True,"['neo mellow', 'singer-songwriter']",John Mayer,"[neo mellow, singer-songwriter]"
24,0i5el041vd6nxrGEU8QRxy,baby you a song you make me wanna roll my wind...,True,"['contemporary country', 'country', 'country p...",Florida Georgia Line,"[contemporary country, country, country pop, c..."
26,5kNe7PE09d6Kvw5pAsx23n,baby last night was hands down one of the best...,True,"['contemporary country', 'country', 'country r...",Thomas Rhett,"[contemporary country, country, country road]"
30,1B8RSIxmwcjad7XUJjeCK2,you make me feel so young you make me feel as ...,True,"['adult standards', 'canadian pop', 'jazz pop'...",Michael Bublé,"[adult standards, canadian pop, jazz pop, lounge]"
...,...,...,...,...,...,...
480814,2QNLwzLyqguTFVCL8KxFsB,doctor captain t o vess r v steadfast bearing ...,True,"['horror punk', 'vancouver punk']",The Darkest of The Hillside Thickets,"[horror punk, vancouver punk]"
480816,5Phnz8K1PB84HfaA5pRwtz,congregation settle in your seats the reverend...,True,"['comic', 'nerdcore']",MC Frontalot,"[comic, nerdcore]"
480820,0JqmQjGr8OUHsoqjo4a84I,i got bitten by a radioactive bug i tried an e...,True,"['geek folk', 'geek rock']",Ookla The Mok,"[geek folk, geek rock]"
480833,5zIV4B3PmT36wxFwFFqIdw,wake up in the morning a suicidal warning pull...,True,['reggae rock'],Bag of Toys,[reggae rock]
480835,2aKPLFSLw1zwbyyFXkrukE,if i had it my way we d be living all night if...,True,"['pop r&b', 'talent show']",David Correy,"[pop r&b, talent show]"

In [11]:
df.columns

Index(['id', 'lyrics', 'is_english', 'genres_list', 'artist_name',
       'parsed_genres'],
      dtype='object')

In [12]:
df.drop(['is_english'], inplace=True, axis=1)

Получим через api ключ у спотифая название песни по id

In [13]:
!pip install spotipy

Collecting spotipy
  Downloading spotipy-2.25.1-py3-none-any.whl.metadata (5.1 kB)
Collecting redis>=3.5.3 (from spotipy)
  Downloading redis-7.1.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: requests>=2.25.0 in /usr/local/lib/python3.12/dist-packages (from spotipy) (2.32.4)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from spotipy) (2.5.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.25.0->spotipy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.25.0->spotipy) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.25.0->spotipy) (2025.11.12)
Downloading spotipy-2.25.1-py3-none-any.whl (31 kB)
Downloading redis-7.1.0-py3-none-any.whl (354 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 354.2/354.2 kB 9.1 MB/s eta 0:00:00
Installing collected packages: redis, spotipy
Successfully installed redis-7.1.0 spotipy-2.25.1

In [14]:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
import time
from tqdm import tqdm  # Прогресс-бар
from google.colab import userdata

In [15]:
try:
    cid = userdata.get('SPOTIFY_CID')      # Проверьте, что имя совпадает
    secret = userdata.get('SPOTIFY_SECRET') # Проверьте, что имя совпадает
except Exception as e:
    print("Ошибка! Не могу найти ключи. Проверьте, включены ли галочки 'Доступ из блокнотов' слева.")
    raise e


# ключи апи
cid = userdata.get('SPOTIFY_CID')
secret = userdata.get('SPOTIFY_SECRET')

# авторизация
client_credentials_manager = SpotifyClientCredentials(client_id=cid, client_secret=secret)
sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)

In [16]:
# тянем функцией названия песен. пакетно по 50, потому что 48к песен

all_ids = df['id'].tolist()

# Сюда будем складывать результаты
found_titles = []
# Размер пачки (Spotify разрешает макс 50)
batch_size = 50

for i in tqdm(range(0, len(all_ids), batch_size)):

  # берем срез 50 штук
  batch_ids = all_ids[i:i+batch_size]
  try:

    # запрос на 50 штук
    results = sp.tracks(batch_ids)
    # разбираем ответ
    for track in results['tracks']:
      if track is not None:
        # найден
        found_titles.append(track['name'])
      else:
        # не найден
        found_titles.append(None)

  except Exception as e:
    print(f"Ошибка в пачке {i}: {e}")
    # Если вся пачка упала
    # заполняем None, чтобы длина списка совпала с длиной DataFrame
    found_titles.extend([None] * len(batch_ids))


  time.sleep(0.1) # чтоб не забанили

df['name_song'] = found_titles

100%|██████████| 1000/1000 [06:07<00:00,  2.72it/s]

In [17]:
df

,id,lyrics,genres_list,artist_name,parsed_genres,name_song
2,7GX5flRQZVHRAGd6B4TmDO,are you alright i m alright i m quite alright ...,"['melodic rap', 'philly rap', 'rap', 'trap']",Lil Uzi Vert,"[melodic rap, philly rap, rap, trap]",XO Tour Llif3
6,50YQFbfIVk2XMnVFKAuuib,we pick up in new york city i m tryna find a m...,"['neo mellow', 'singer-songwriter']",John Mayer,"[neo mellow, singer-songwriter]","Whiskey, Whiskey, Whiskey"
24,0i5el041vd6nxrGEU8QRxy,baby you a song you make me wanna roll my wind...,"['contemporary country', 'country', 'country p...",Florida Georgia Line,"[contemporary country, country, country pop, c...",Cruise
26,5kNe7PE09d6Kvw5pAsx23n,baby last night was hands down one of the best...,"['contemporary country', 'country', 'country r...",Thomas Rhett,"[contemporary country, country, country road]",Die A Happy Man
30,1B8RSIxmwcjad7XUJjeCK2,you make me feel so young you make me feel as ...,"['adult standards', 'canadian pop', 'jazz pop'...",Michael Bublé,"[adult standards, canadian pop, jazz pop, lounge]",You Make Me Feel so Young
...,...,...,...,...,...,...
480814,2QNLwzLyqguTFVCL8KxFsB,doctor captain t o vess r v steadfast bearing ...,"['horror punk', 'vancouver punk']",The Darkest of The Hillside Thickets,"[horror punk, vancouver punk]",A Marine Biologist
480816,5Phnz8K1PB84HfaA5pRwtz,congregation settle in your seats the reverend...,"['comic', 'nerdcore']",MC Frontalot,"[comic, nerdcore]",Origin Of Species
480820,0JqmQjGr8OUHsoqjo4a84I,i got bitten by a radioactive bug i tried an e...,"['geek folk', 'geek rock']",Ookla The Mok,"[geek folk, geek rock]",Super Powers
480833,5zIV4B3PmT36wxFwFFqIdw,wake up in the morning a suicidal warning pull...,['reggae rock'],Bag of Toys,[reggae rock],The Raven
480835,2aKPLFSLw1zwbyyFXkrukE,if i had it my way we d be living all night if...,"['pop r&b', 'talent show']",David Correy,"[pop r&b, talent show]",My Way

In [18]:
df.to_csv('genius_songs_complete.csv', index=False, encoding='utf-8-sig')

print("Файл сохранен во временное хранилище Colab!")

Файл сохранен во временное хранилище Colab!

Генерализация жанров. hip-hop, rock, pop, country, rap

In [19]:
display(genre_counts.head(20))

Unknown genre        4352
rock                 3762
hip hop              2367
rap                  2154
dance pop            2151
pop rock             2062
classic rock         1969
mellow gold          1913
country rock         1872
indie rock           1871
alternative rock     1866
pop rap              1855
country              1617
singer-songwriter    1599
adult standards      1596
pop                  1577
soft rock            1554
alternative metal    1546
modern rock          1505
gangster rap         1460
Name: count, dtype: int64

mellow gold - выкинул, но вроде это поджанр раннего рока, adult standarts - для бумеров - скип

In [20]:
def simplify_genre(genre_str):
    # Приводим к нижнему регистру на всякий случай
    g = str(genre_str).lower()

    # Приоритеты (если там и поп и рок, выберем рок)
    if 'rap' in g or 'hip hop' in g or 'trap' in g or 'drill' in g:
        return 'Hip-Hop'
    elif 'metal' in g or 'punk' in g or 'rock' in g or 'grunge' in g or 'alternative' in g:
        return 'Rock'
    elif 'country' in g:
        return 'Country'
    elif 'pop' in g or 'singer' in g or 'songwriter' in g:
        return 'Pop'
    else:
        return 'Other'

In [21]:
# применим генералищацию тпов
df['main_genre'] = df['genres_list'].apply(simplify_genre)
# выкинем parsed_genres, т.к. дублирует
df.drop('parsed_genres', axis=1, inplace=True)

In [22]:
print(df['main_genre'].value_counts())

main_genre
Rock       20383
Other      14616
Hip-Hop     7036
Pop         6757
Country     1193
Name: count, dtype: int64

*Чистим текст песни от стоп слов, т.к. LSA чувствителен"*

In [23]:
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# Часто бывает в датасете "verse", "hook", "lyrics" в самом начале или конце
custom_stops = {'verse', 'chorus', 'intro', 'outro', 'bridge', 'lyrics'}
stop_words.update(custom_stops)

def remove_stopwords(text):
    if not isinstance(text, str):
        return ""
    # Текст уже в нижнем регистре, просто сплитим
    words = text.split()
    # Оставляем слова, которых нет в стоп-листе и которые длиннее 2 букв
    filtered = [w for w in words if w not in stop_words and len(w) > 2]
    return " ".join(filtered)

df['clean_text'] = df['lyrics'].apply(remove_stopwords)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [24]:
df.shape

(49985, 7)

In [25]:
# сделаем фильтрацию где в cleaned_text есть только текст
# Оставляем только те строки, где clean_text НЕ равен пустой строке
df = df[df['clean_text'] != ""]
# Оставляем только те строки, где clean_text НЕ равен пустой строке
df = df[df['clean_text'] != ""]
# Удаляет строки, где clean_text является NaN
df = df.dropna(subset=['clean_text'])
df = df.reset_index(drop=True)   # Сбрасываем индекс

print(f'after cleaning {df.shape}')

after cleaning (49982, 7)

In [27]:
df = df[df['main_genre'] != 'Country']

# 2. ОБЯЗАТЕЛЬНО сбрасываем индексы
# Если этого не сделать, у тебя будут дырки в нумерации (0, 2, 5...),
# и бот упадет с ошибкой "index out of bounds"
df.reset_index(drop=True, inplace=True)

print(f"Готово. Новый размер датасета: {df.shape}")#

Готово. Новый размер датасета: (48789, 7)

In [30]:
# здесь код на то, чтобы вобрать в себя побольше сжмплов
df['main_genre'].value_counts()
# берем по 6700

main_genre
Rock       20383
Other      14613
Hip-Hop     7036
Pop         6757
Name: count, dtype: int64

# СТОП!! БЕРЕМ БОЛЬШЕ СЭМПЛОВ, ВЫКИДЫВАЕМ КАНТРИ

Сэмплирование
Если "Pop" будет 100к песен, а "Rock" 5к, то Попса задавит всё векторное пространство и анализ не репрезентативный будет

 * Почему?

* Ответ: SVD (LSA) работает на основе дисперсии (разброса данных). Если у тебя 20,000 песен Рока и всего 1,000 Кантри, алгоритм решит, что Рок — это и есть вся вселенная, а Кантри — это просто статистическая погрешность (шум).

In [31]:
# все главные категории
df_clean = df[df['main_genre'] != 'Other']

# 2. Делаем балансировку
# n=1100 — сколько брать, чтобы взять country жанр
# Метод sample сам по себе берет строки в случайном порядке
df_balanced = df_clean.groupby('main_genre').sample(n=6700, random_state=52)

In [32]:
# Перемешиваем весь итоговый датасет, чтобы жанры шли не блоками, а вперемешку
df_balanced = df_balanced.sample(frac=1, random_state=42).reset_index(drop=True)

# Проверяем результат
print(df_balanced['main_genre'].value_counts())

main_genre
Pop        6700
Hip-Hop    6700
Rock       6700
Name: count, dtype: int64

# !!! важный момент, если вдруг country после чистки меньше 1100, то алгоритму хана. надеюсь что предыдущие строки очистки корректно сработали

UPD: ВСЁ ЧЕТЁНЬКО

In [33]:
country_df = df[df['main_genre'] == 'country']
# Склеиваем весь текст жанра Country в одну большую строку и разбиваем на слова
all_words = ' '.join(country_df['clean_text']).split()
# Проверить, есть ли слова короче 3 букв (должен быть пустой список или очень мало специфичных)
short_words = [w for w in all_words if len(w) <= 2]
print(f"Примеры коротких слов (если есть): {len(short_words)}")

Примеры коротких слов (если есть): 0

## Отказываемся от стемминга в пользу лемматиации

In [34]:
from nltk.stem import WordNetLemmatizer

# Скачиваем словарь для лемматизации
nltk.download('wordnet')
nltk.download('omw-1.4')

lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    if not isinstance(text, str):
        return ""
    words = text.split()
    # Лемматизируем каждое слово (приводим к базе)
    # pos='v' означает "глагол" (verb). Это поможет превратить singing -> sing
    # Можно лемматизировать без pos, но с глаголами эффективнее для песен
    lemmatized_words = [lemmatizer.lemmatize(w, pos='v') for w in words]
    return " ".join(lemmatized_words)

# Применяем к нашей сбалансированной таблице
# Используй ту колонку, где уже убраны стоп-слова (clean_text или как ты её назвал)
df_balanced['final_text'] = df_balanced['clean_text'].apply(lemmatize_text)

# Смотрим пример до и после
print("До:", df_balanced['clean_text'].iloc[0][:50])
print("После:", df_balanced['final_text'].iloc[0][:50])

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

До: fading scent summertime arbutus trees firs glisten
После: fade scent summertime arbutus tree firs glisten ra

Мы закончили с этапом предобработки датасета!!!
переходим к алгоритму SVD, но он будет в проекте 2

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [36]:
df_balanced.to_csv('dataset_recsys_telegramm_bot')
# сохранил уже 6700 песен по 3 жанра

In [37]:
df

,id,lyrics,genres_list,artist_name,name_song,main_genre,clean_text
0,7GX5flRQZVHRAGd6B4TmDO,are you alright i m alright i m quite alright ...,"['melodic rap', 'philly rap', 'rap', 'trap']",Lil Uzi Vert,XO Tour Llif3,Hip-Hop,alright alright quite alright money right coun...
1,50YQFbfIVk2XMnVFKAuuib,we pick up in new york city i m tryna find a m...,"['neo mellow', 'singer-songwriter']",John Mayer,"Whiskey, Whiskey, Whiskey",Pop,pick new york city tryna find man never got pu...
2,0i5el041vd6nxrGEU8QRxy,baby you a song you make me wanna roll my wind...,"['contemporary country', 'country', 'country p...",Florida Georgia Line,Cruise,Rock,baby song make wanna roll windows cruise hey b...
3,1B8RSIxmwcjad7XUJjeCK2,you make me feel so young you make me feel as ...,"['adult standards', 'canadian pop', 'jazz pop'...",Michael Bublé,You Make Me Feel so Young,Pop,make feel young make feel spring sprung every ...
4,2TR7A4ulH9R1PNwMyd8o8U,the mixtapes got a little hank little drake a ...,"['contemporary country', 'country', 'country p...",Florida Georgia Line,This Is How We Roll,Rock,mixtapes got little hank little drake little s...
...,...,...,...,...,...,...,...
48784,2QNLwzLyqguTFVCL8KxFsB,doctor captain t o vess r v steadfast bearing ...,"['horror punk', 'vancouver punk']",The Darkest of The Hillside Thickets,A Marine Biologist,Rock,doctor captain vess steadfast bearing west hes...
48785,5Phnz8K1PB84HfaA5pRwtz,congregation settle in your seats the reverend...,"['comic', 'nerdcore']",MC Frontalot,Origin Of Species,Other,congregation settle seats reverend front aloud...
48786,0JqmQjGr8OUHsoqjo4a84I,i got bitten by a radioactive bug i tried an e...,"['geek folk', 'geek rock']",Ookla The Mok,Super Powers,Rock,got bitten radioactive bug tried experimental ...
48787,5zIV4B3PmT36wxFwFFqIdw,wake up in the morning a suicidal warning pull...,['reggae rock'],Bag of Toys,The Raven,Rock,wake morning suicidal warning pull shades back...
48788,2aKPLFSLw1zwbyyFXkrukE,if i had it my way we d be living all night if...,"['pop r&b', 'talent show']",David Correy,My Way,Pop,way living night way holding jobs way worry bo...

In [38]:
df_balanced.drop(['clean_text', 'lyrics'], inplace = True, axis = 1)

In [39]:
df_balanced.to_csv('dataset_recsys_telegramm_bot2.csv')